<?php
/**
 * @file
 * Alma Reminder Service module.
 *
 * Provide desired sms and/or email notifications.
 */

define('ALMA_REMINDER_SMS_SERVICE_COST', 3);
define('ALMA_REMINDER_EMAIL_SERVICE_COST', 3);

/**
 * Implements hook_user_view().
 */
function alma_reminder_service_user_view($account) {
  $info = alma_reminder_service_get_patron();

  if (!$info->service_enabled) {
    watchdog('alma_reminder_service', 'Alma reminder service not enabled on this instance.', array(), WATCHDOG_DEBUG);
    return;
  }

  $sms = FALSE;
  // SMS default checked?
  if (isset($info->messages[0]) && $info->messages[0]['value'] == 'sms' || isset($info->messages[1]) && $info->messages[1]['value'] == 'sms') {
    $sms = TRUE;
  }

  $email = FALSE;
  // Email default checked?
  if (isset($info->messages[0]) && $info->messages[0]['value'] == 'email' || isset($info->messages[1]) && $info->messages[1]['value'] == 'email') {
    $email = TRUE;
  }

  // Add SMS checkbox.
  $account->content['alma_user_sms'] = array(
    '#prefix' => '<div class="alma-reminder-service">',
    '#title' => t('SMS reminders'),
    '#type' => 'item',
    '#markup' => ($sms) ? t('You are subscribed') : t('You are not subscribed'),
    '#weight' => 10,
    '#suffix' => '</div>',
  );
  // Add email checkbox.
  $account->content['alma_user_email'] = array(
    '#prefix' => '<div class="email_service">',
    '#title' => t('Email reminders'),
    '#type' => 'item',
    '#markup' => ($email) ? t('You are subscribed') : t('You are not subscribed'),
    '#weight' => 11,
    '#suffix' => '</div>',
  );
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function alma_reminder_service_form_user_profile_form_alter(&$form, &$form_state) {
  $info = alma_reminder_service_get_patron();

  if (!$info->service_enabled) {
    watchdog('alma_reminder_service', 'Alma reminder service not enabled on this instance.', array(), WATCHDOG_DEBUG);
    return;
  }

  $sms = FALSE;
  // SMS default checked?
  if (isset($info->messages[0]) && $info->messages[0]['value'] == 'sms' || isset($info->messages[1]) && $info->messages[1]['value'] == 'sms') {
    $sms = TRUE;
  }

  $email = FALSE;
  // Email default checked?
  if (isset($info->messages[0]) && $info->messages[0]['value'] == 'email' || isset($info->messages[1]) && $info->messages[1]['value'] == 'email') {
    $email = TRUE;
  }

  $sms_service_cost = variable_get('alma_reminder_sms_service_cost', ALMA_REMINDER_SMS_SERVICE_COST);
  $email_service_cost = variable_get('alma_reminder_email_service_cost', ALMA_REMINDER_EMAIL_SERVICE_COST);
  // Add SMS checkbox.
  $form['alma_user_sms'] = array(
    '#prefix' => '<div class="alma-reminder-service"><div class="sms-service">' . t('By checking this, you accept our <a href="/paamindelsesservice" target="_blank">terms</a>') . '.</p>',
    '#title' => t('SMS reminders'),
    '#type' => 'checkbox',
    '#return_value' => '1',
    '#default_value' => $sms,
    '#weight' => -2,
    '#suffix' => '<div class="reminder-note">' . t('Price: @price DKK per piece', array('@price' => $sms_service_cost)) . '</div></div>',
  );

  // Add email checkbox.
  $form['alma_user_email'] = array(
    '#prefix' => '<div class="email-service">',
    '#title' => t('Email reminders'),
    '#type' => 'checkbox',
    '#return_value' => '1',
    '#default_value' => $email,
    '#suffix' => '<div class="reminder-note">' . t('Price: @price DKK per piece', array('@price' => $email_service_cost)) . '</div></div></div>',
    '#weight' => -1,
  );

  $form['#attached']['css'][] = drupal_get_path('module', 'alma_reminder_service') . '/css/alma_reminder_service.styles.css';

  // Additional handler to submit changes to ALMA.
  $form['#submit'][] = 'alma_reminder_service_user_profile_submit';
}

/**
 * Additional handler for user_profile submit to
 *  save checkbox settings via ALMA.
 */
function alma_reminder_service_user_profile_submit($form, &$form_state) {
  $creds = ding_user_get_creds();

  $action = 'remove_message_service';
  if (!empty($form_state['values']['alma_user_sms'])) {
    $action = 'add_message_service';
  }
  alma_client_invoke($action, $creds['name'], $creds['pass'], ALMA_SERVICE_METHOD_SMS, ALMA_SERVICE_TYPE_DUE_DATE_ALERT);

  $action = 'remove_message_service';
  if (!empty($form_state['values']['alma_user_email'])) {
    $action = 'add_message_service';
  }
  alma_client_invoke($action, $creds['name'], $creds['pass'], ALMA_SERVICE_METHOD_EMAIL, ALMA_SERVICE_TYPE_DUE_DATE_ALERT);
}

/**
 * Implement hook_form_alter().
 */
function alma_reminder_service_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'alma_settings_form') {
    $form['alma_reminder_service'] = array(
      '#type' => 'fieldset',
      '#title' => t('Alma reminder service'),
      '#collapsible' => FALSE,
      '#collapsed' => FALSE,
    );

    $form['alma_reminder_service']['alma_reminder_sms_service_cost'] = array(
      '#type' => 'textfield',
      '#title' => t('SMS reminder cost'),
      '#description' => t('SMS reminder cost, in DKK.'),
      '#default_value' => variable_get('alma_reminder_sms_service_cost', ALMA_REMINDER_SMS_SERVICE_COST),
      '#size' => 2,
      '#element_validate' => array('element_validate_integer_positive'),
    );

    $form['alma_reminder_service']['alma_reminder_email_service_cost'] = array(
      '#type' => 'textfield',
      '#title' => t('E-Mail reminder cost'),
      '#description' => t('E-Mail reminder cost, in DKK.'),
      '#default_value' => variable_get('alma_reminder_email_service_cost', ALMA_REMINDER_EMAIL_SERVICE_COST),
      '#size' => 2,
      '#element_validate' => array('element_validate_integer_positive'),
    );
  }
}

/**
 * New client.
 */
function alma_reminder_service_client() {
  /*
   * This is basically a singleton. We also wait until right before
   *  instantiating to include our required classes. That seems like a
   *  decent performance tradeoff instead of loading everything on every
   *  page load.
   */
  static $client;
  if (!isset($client)) {
    try {
      $client = new Smsservice(variable_get('alma_base_url', ''));
    }
    catch (Exception $e) {
      watchdog_exception('alma_reminder_service', $e);
      throw $e;
    }
  }

  return $client;
}

/**
 * New client to invoke custom changes.
 */
function alma_reminder_service_client_invoke($method) {
  $args = func_get_args();
  // Lose the method.
  array_shift($args);

  try {
    $client = alma_reminder_service_client();
    $result = call_user_func_array(array($client, $method), $args);
  }
  catch (Exception $e) {
    watchdog_exception('alma_reminder_service', $e);
    throw $e;
  }

  return $result;
}

/**
 * Retrieve patron (user) information from DDE.
 *
 * @param array $creds
 *   User credentials, if any. Otherwise they will be fetched on runtine.
 * @param boolean $reset
 *   Whether to make a fresh request for user data.
 * @param boolean $as_array
 *   Whether return results as array, instead of object.
 *
 * @return mixed
 *   User data, as array OR object.
 */
function alma_reminder_service_get_patron($creds = NULL, $reset = FALSE, $as_array = FALSE) {
  if (is_null($creds)) {
    // Get creds, which may throw an exception that login is required.
    global $user;

    try {
      $creds = ding_user_get_creds($user);
    }
    catch (DingProviderAuthException $e) {
      return NULL;
    }
  }

  static $patron;
  if (!$patron || $reset) {
    $info = alma_reminder_service_client_invoke('GetPatronInfo', $creds['name'], $creds['pass'], TRUE);
    $patron = array(
      // The missing part.
      'messages' => isset($info['sendMethods']) ? $info['sendMethods'] : '',
      'service_enabled' => $info['messageServices'],
    );
  }

  if ($as_array) {
    return $patron;
  }

  return (object) $patron;
}
