<?php

/**
 * @file
 *
 * Implements sms and email checkboxes in user profile and in
 *  user edit form to save changes.
 */

module_load_include('inc', 'sms_service', 'sms_service');

/**
 * Implements hook_user_view().
 */
function sms_service_user_view($account) {

  $info = sms_service_get_patron();
  if (is_null($info)) {
    return;
  }

  // SMS default checked?
  if (isset($info->messages[0]) && $info->messages[0]['value'] == 'sms' || isset($info->messages[1]) && $info->messages[1]['value'] == 'sms') {
    $sms = 'checked="checked"';
  }
  else {
    $sms = '';
  }

  // Email default checked?
  if (isset($info->messages[0]) && $info->messages[0]['value'] == 'email' || isset($info->messages[1]) && $info->messages[1]['value'] == 'email') {
    $email = 'checked="checked"';
  }
  else {
    $email = '';
  }

  // Add SMS checkbox.
  $account->content['alma_user_sms'] = array(
   '#prefix'  => '<div class="sms_service">',
    '#title'  => t('SMS reminders'),
    '#type'   => 'item',
    '#markup' => '<input type="checkbox" ' . $sms . ' class="form-checkbox" disabled=TRUE >' . t(' Price: 3 DKK per piece') . '.',
    '#weight' => 10,
    '#suffix' => '</div>',
  );

  // Add email checkbox.
  $account->content['alma_user_email'] = array(
   '#prefix'  => '<div class="email_service">',
    '#title'  => t('Email reminders'),
    '#type'   => 'item',
    '#markup' => '<input type="checkbox" ' . $email . ' class="form-checkbox" disabled=TRUE >' . t(' Price: 3 DKK per piece') . '.',
    '#weight' => 11,
    '#suffix' => '</div>',
  );
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function sms_service_form_user_profile_form_alter(&$form, &$form_state) {

  $info = sms_service_get_patron();
  if (is_null($info)) {
    return;
  }

  // SMS default checked?
  if (isset($info->messages[0]) && $info->messages[0]['value'] == 'sms' || isset($info->messages[1]) && $info->messages[1]['value'] == 'sms') {
    $sms = '1';
  }
  else {
    $sms = '0';
  }

  // Email default checked?
  if (isset($info->messages[0]) && $info->messages[0]['value'] == 'email' || isset($info->messages[1]) && $info->messages[1]['value'] == 'email') {
    $email = '1';
  }
  else {
    $email = '0';
  }

  // Add SMS checkbox.
  $form['alma_user_sms'] = array(
    '#prefix'        => '<div class="smsservice"><div class="sms_service">' . t('By checking this, you accept our <a href="/paamindelsesservice" target="_blank">terms</a>') . '.</p>',
    '#title'         => t('SMS reminders'),
    '#type'          => 'checkbox',
    '#return_value'  => '1',
    '#default_value' => $sms,
    '#weight'        => -2,
    '#suffix'        => '</div>',
  );

  // Add email checkbox.
  $form['alma_user_email'] = array(
   '#prefix'         => '<div class="email_service">',
    '#title'         => t('Email reminders'),
    '#type'          => 'checkbox',
    '#return_value'  => '1',
    '#default_value' => $email,
    '#suffix'        => '</div></div>',
    '#weight'        => -1,
  );
  // Additional handler to submit changes to ALMA.
  $form['#submit'][] = 'sms_service_user_profile_submit';
}

/**
 * Additional handler for user_profile submit to
 *  save checkbox settings via ALMA.
 */
function sms_service_user_profile_submit($form, &$form_state) {
  $creds = ding_user_get_creds();

  if ($form_state['values']['alma_user_sms']['return_value'] == '1') {
    // Add a due date alerts as SMS service per default.
    alma_client_invoke('add_message_service', $creds['name'], $creds['pass'], ALMA_SERVICE_METHOD_SMS, ALMA_SERVICE_TYPE_DUE_DATE_ALERT);
  }
  // Also remove SMS messaging service.
  else {
    alma_client_invoke('remove_message_service', $creds['name'], $creds['pass'], ALMA_SERVICE_METHOD_SMS, ALMA_SERVICE_TYPE_DUE_DATE_ALERT);
  }
  // Also add email messaging service.
  if ($form_state['values']['alma_user_email']['return_value'] == '1') {
    // Add a due date alerts as email service per default.
    alma_client_invoke('add_message_service', $creds['name'], $creds['pass'], ALMA_SERVICE_METHOD_EMAIL, ALMA_SERVICE_TYPE_DUE_DATE_ALERT);
  }
  // Also remove email messaging service.
  else {
    alma_client_invoke('remove_message_service', $creds['name'], $creds['pass'], ALMA_SERVICE_METHOD_EMAIL, ALMA_SERVICE_TYPE_DUE_DATE_ALERT);
  }
}

